package com.modules;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.modules.Tabla;

import com.modules.TablaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tablaDaoConfig;

    private final TablaDao tablaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tablaDaoConfig = daoConfigMap.get(TablaDao.class).clone();
        tablaDaoConfig.initIdentityScope(type);

        tablaDao = new TablaDao(tablaDaoConfig, this);

        registerDao(Tabla.class, tablaDao);
    }
    
    public void clear() {
        tablaDaoConfig.getIdentityScope().clear();
    }

    public TablaDao getTablaDao() {
        return tablaDao;
    }

}
