package com.modules;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TABLA.
 */
public class Tabla {

    private Long id;
    private String fila1;
    private String fila2;
    private String fila3;

    public Tabla() {
    }

    public Tabla(Long id) {
        this.id = id;
    }

    public Tabla(Long id, String fila1, String fila2, String fila3) {
        this.id = id;
        this.fila1 = fila1;
        this.fila2 = fila2;
        this.fila3 = fila3;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFila1() {
        return fila1;
    }

    public void setFila1(String fila1) {
        this.fila1 = fila1;
    }

    public String getFila2() {
        return fila2;
    }

    public void setFila2(String fila2) {
        this.fila2 = fila2;
    }

    public String getFila3() {
        return fila3;
    }

    public void setFila3(String fila3) {
        this.fila3 = fila3;
    }

}
